# Generated by Django 6.0.1 on 2026-02-05 03:03

import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documenttag',
            name='documents_d_documen_8c4441_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documentmetadata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documenttag',
            name='color',
            field=models.CharField(default=documents.models.get_random_color, max_length=7),
        ),
        migrations.AddIndex(
            model_name='documenttag',
            index=models.Index(fields=['document', 'tag', 'owner'], name='documents_d_documen_1c3fcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentmetadata',
            constraint=models.UniqueConstraint(fields=('document', 'key'), name='unique_metadata_per_doc'),
        ),
        migrations.AddConstraint(
            model_name='documenttag',
            constraint=models.UniqueConstraint(fields=('document', 'tag', 'owner'), name='unique_document_tag_per_user'),
        ),
    ]
